models/Lead.php
<?php

namespace app\models;
use yii\db\ActiveRecord;
use yii\behaviors\BlameableBehavior;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "lead".
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property string $notes
 * @property integer $status
 * @property integer $owner
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 */
class Lead extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lead';
    }

    /**
     * @inheritdoc
     */
     public function rules()
    {
		$rules = []; 
		$stringItems = [['notes'], 'string'];
		$integerItems  = ['status', 'created_at', 'updated_at', 'created_by', 'updated_by'];		
		if (\Yii::$app->user->can('updateLead')) {
			$integerItems[] = 'owner';
		}
		$integerRule = [];
		$integerRule[] = $integerItems;
		$integerRule[] = 'integer';
		$ShortStringItems = [['name', 'email', 'phone'], 'string', 'max' => 255]; 
		$rules[] = $stringItems;
		$rules[] = $integerRule;
		$rules[] = $ShortStringItems;		
		return $rules;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'email' => 'Email',
            'phone' => 'Phone',
            'notes' => 'Notes',
            'status' => 'Status',
            'owner' => 'Owner',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }
	
	 public function behaviors()
    {
		return 
		[
			[
				'class' => BlameableBehavior::className(),
				'createdByAttribute' => 'created_by',
				'updatedByAttribute' => 'updated_by',
			 ],
				'timestamp' => [
				'class' => 'yii\behaviors\TimestampBehavior',
				'attributes' => [
					ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
					ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
				],
			],
		];
    }
	
	public function getFullname(){
		return $this->name;
	}
	
	public function getId(){
		return $this->id;
	}
	
	public function getUserOwner(){
		
		return $this->hasOne(User::className(), ['id' => 'owner']);
	}
	
	public function getCreatedby(){
		
		return $this->hasOne(User::className(), ['id' => 'created_by']);
	}
	
	public function getUpdatedby(){
		
		return $this->hasOne(User::className(), ['id' => 'updated_by']);
	}
	
	public function getStatusItem(){
		
		return $this->hasOne(Status::className(), ['id' => 'status']);
	}
	public static function getLeads()
	{
		$allLeads = self::find()->all();
		$allLeadsArray = ArrayHelper::
					map($allLeads, 'id', 'name');
		return $allLeadsArray;						
	}
	
	//Get a list of leads that have made deals
	public static function getLeadsWithDeals()
	{
		$leads = self::getLeads();
		//Check if lead has any deals. If not, it is unset from the array		
		foreach ($leads as $key => $lead) {
			if (Deal::findDealFromLead($key)==NULL) {
				unset($leads[$key]);
			}
		}
		
		
		$leads[-1] = 'All Leads';
		$leads = array_reverse ( $leads, true );
		return $leads;	
	}
	
	//Find all deals made by a single Lead
	public static function getAllDeals($leadId){
		$deals=Deal::findAll([
			'leadId' => $leadId,
		]);
		
		$allLeadsArray = ArrayHelper::
					map($deals,'id', 'name');
		return $allLeadsArray;
	}
}

controllers/DealController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Deal;
use app\models\DealSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;
use app\models\Lead;

/**
 * DealController implements the CRUD actions for Deal model.
 */
class DealController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Deal models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DealSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'leadIds' => Lead::getLeadsWithDeals(),
			'leadId' => $searchModel->leadId,
        ]);
    }

    /**
     * Displays a single Deal model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Deal model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (!\Yii::$app->user->can('createDeal'))
			throw new UnauthorizedHttpException ('Hey, You are not allowed to create new deals');
		
		$model = new Deal();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Deal model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if (!\Yii::$app->user->can('updateDeal'))
			throw new UnauthorizedHttpException ('Hey, You are not allowed to update deals');
		
		$model = $this->findModel($id);
		

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Deal model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (!\Yii::$app->user->can('deleteDeal'))
			throw new UnauthorizedHttpException ('Hey, You are not allowed to delete deals');
		
		$this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Deal model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Deal the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Deal::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/LeadController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Lead;
use app\models\Status;
use app\models\LeadSearch;
use app\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UnauthorizedHttpException;
use app\models\DealSearch;

/**
 * LeadController implements the CRUD actions for Lead model.
 */
class LeadController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Lead models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new LeadSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'owners' => User::getUsersWithAllUsers(),
			'owner' => $searchModel->owner,
			'statuses' => Status::getStatusWithAllStatuses(),
			'status' => $searchModel->status,
        ]);
    }

    /**
     * Displays a single Lead model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {		
		return $this->render('view', [
            'model' => $this->findModel($id),
			'allDeals' => Lead::getAllDeals($id),
        ]);
    }

    /**
     * Creates a new Lead model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (!\Yii::$app->user->can('createLead'))
			throw new UnauthorizedHttpException ('Hey, You are not allowed to create new leads');
		
		$model = new Lead();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Lead model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		
		if (!\Yii::$app->user->can('updateLead') && 
		    !\Yii::$app->user->can('updateOwnLead', ['lead' =>$model]) )
			throw new UnauthorizedHttpException ('Hey, You are not allowed to update leads');
			
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Lead model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (!\Yii::$app->user->can('updateLead'))
			throw new UnauthorizedHttpException ('Hey, You are not allowed to delete leads');
		
		$this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Lead model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Lead the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Lead::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/lead/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Status;
use app\models\User;

/* @var $this yii\web\View */
/* @var $model app\models\Lead */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="lead-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'notes')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'status')->
				dropDownList(Status::getStatuses()) ?>   
				
	<?php 
		if (\Yii::$app->user->can('updateLead')) { ?>
		<?= $form->field($model, 'owner')-> dropDownList(User::getUsers()); ?>
	<?php }?>  


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/lead/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\LeadSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="lead-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'phone') ?>

    <?= $form->field($model, 'notes') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'owner') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/lead/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Lead */

$this->title = 'Create Lead';
$this->params['breadcrumbs'][] = ['label' => 'Leads', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lead-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/lead/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\LeadSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Leads';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lead-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
		<?php if(\Yii::$app->user->can('createLead')){ ?>
        <?= Html::a('Create Lead', ['create'], ['class' => 'btn btn-success']) ?>
		<?php } ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'email:email',
            'phone',
            'notes:ntext',
            [
				'attribute' => 'status',
				'label' => 'Status',
				'format' => 'raw',
				'value' => function ($model) {
					return $model->statusItem->name;
				},
				'filter'=>Html::dropDownList('LeadSearch[status]', $status, $statuses, ['class'=>'form-control']),
			],
            [
				'attribute' => 'owner',
				'label' => 'Owner',
				'format' => 'raw',
				'value' => function($model){
					return Html::a($model->userOwner->fullname, 
					['user/view', 'id' => $model->userOwner->id]);
				},
				'filter'=>Html::dropDownList('LeadSearch[owner]', $owner, $owners, ['class'=>'form-control']),
			],
            // 'created_at',
            // 'updated_at',
            // 'created_by',
            // 'updated_by',

            ['class' => 'yii\grid\ActionColumn',
			'visibleButtons' => [
			'delete' => (\Yii::$app->user->can('updateLead')),
			],
			],
        ],
    ]); ?>
</div>

views/lead/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Lead */

$this->title = 'Update Lead: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Leads', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="lead-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/lead/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Lead */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Leads', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="lead-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
		<?php if (\Yii::$app->user->can('updateLead') || 
		    \Yii::$app->user->can('updateOwnLead', ['lead' =>$model]) ) { ?>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
			<?php } ?>
		<?php if (\Yii::$app->user->can('updateLead')){ ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
		<?php } ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'email:email',
            'phone',
            'notes:ntext',
			[ // the status name
				'label' => $model->attributeLabels()['status'],
				'value' => $model->statusItem->name,			
			],	
			[ // the owner name of the lead
				'label' => $model->attributeLabels()['owner'],
				'format' => 'html',
				'value' => Html::a($model->userOwner->fullname, 
					['user/view', 'id' => $model->userOwner->id]),			
			],
			[ // created_at
				'label' => $model->attributeLabels()['created_at'],
				'format' => 'html',
				'value' => isset($model->created_at) ? date('d/m/y H:i:s' ,$model->created_at) : "No Data",			
			],
			[ // updated_at
				'label' => $model->attributeLabels()['updated_at'],
				'format' => 'html',
				'value' => isset($model->updated_at) ? date('d/m/y H:i:s' ,$model->updated_at) : "No Data",			
			],
            [ // created By
				'label' => $model->attributeLabels()['created_by'],
				'format' => 'html',
				'value' => isset($model->createdby->fullname) ? (Html::a($model->createdby->fullname, 
					['user/view', 'id' => $model->createdby->id])) : "No Data" ,			
			],
			[ // updated By
				'label' => $model->attributeLabels()['updated_by'],
				'format' => 'html',
				'value' => isset($model->updatedby->fullname) ? (Html::a($model->updatedby->fullname, 
					['user/view', 'id' => $model->updatedby->id])) : "No Data" ,			
			],
			
        ],
    ]) ?>
	<table>
	<tr>
		<th>Deals made by this Lead</th>
	</tr>
	<?php
	if (!empty($allDeals)){
		foreach($allDeals as $id => $name){
		echo '<tr><td>';	
		echo Html::a('Deal No.'.$id.': '.$name, ['deal/view', 'id' => $id]);
		echo '</td></tr>';
		}
	}
	else{
		echo "<tr><td>No Deals For this Lead</td></tr>";
	}

	?>
	</table>
	

</div>